# -*-coding:utf-8-*-

import spider_lashou

site_spider_map = {
    'lashou' : [spider_lashou.SpiderLashou],
    'meituan' : [spider_lashou.SpiderMeituan],
    }


city_list = {
    'beijing' : ['北京', 100],
    'shanghai' : ['上海', 99],
    'guangzhou' : ['广州', 98],
    'shenzhen' : ['深圳', 97],
    'wuhan' : ['武汉', 96],
    'hangzhou' : ['杭州', 95],
    'tianjin' : ['天津', 94],
    'nanjing' : ['南京', 93],
    'chengdu' : ['成都', 92],
    'chongqing' : ['重庆', 91],
    'shenyang' : ['沈阳', 90],
    'suzhou' : ['苏州', 89],
    'wuxi' : ['无锡', 88],
    'xian' : ['西安', 87],
    'zhengzhou' : ['郑州', 86],
    'dalian' : ['大连', 85],
    'qingdao' : ['青岛', 84],
    'changsha' : ['长沙', 83],
    'hefei' : ['合肥', 82],
    'taiyuan' : ['太原', 81],
    'fuzhou' : ['福州', 80],
    'kunming' : ['昆明', 79],
    'shijiazhuang' : ['石家庄', 78],
    'jinan' : ['济南', 77],
    'xiamen' : ['厦门', 76],
    'langfang' : ['廊坊', 75],
    'nanchang' : ['南昌', 74],
    'fushun' : ['抚顺', 73],
    'ningbo' : ['宁波', 72],
    'changzhou' : ['常州', 71],
    'haerbin' : ['哈尔滨', 70],
    'baoding' : ['保定', 69],
    'shaoxing' : ['绍兴', 68],
    'changchun' : ['长春', 67],
    
    'quanguo' : ['全国', 0],
    }

site_list = {
    'lashou' : ['拉手网', 'http://www.lashou.com', 100],
    'meituan' : ['美团', 'http://www.meituan.com', 99],
    }

site_city_list = {
    ['lashou', 'beijing'] : ['拉手网-北京', 'http://www.lashou.com/beijing'],
    ['lashou', 'shanghai'] : ['拉手网-上海', 'http://www.lashou.com/shanghai'],
    ['lashou', 'guangzhou'] : ['拉手网-广州', 'http://www.lashou.com/guangzhou'],
    ['lashou', 'shenzhen'] : ['拉手网-深圳', 'http://www.lashou.com/shenzhen'],
    ['lashou', 'wuhan'] : ['拉手网-武汉', 'http://www.lashou.com/wuhan'],
    ['lashou', 'hangzhou'] : ['拉手网-杭州', 'http://www.lashou.com/hangzhou'],
    ['lashou', 'tianjin'] : ['拉手网-天津', 'http://www.lashou.com/tianjin'],
    ['lashou', 'nanjing'] : ['拉手网-南京', 'http://www.lashou.com/nanjing'],
    ['lashou', 'chengdu'] : ['拉手网-成都', 'http://www.lashou.com/chengdu'],
    ['lashou', 'chongqing'] : ['拉手网-重庆', 'http://www.lashou.com/chongqing'],
    ['lashou', 'shenyang'] : ['拉手网-沈阳', 'http://www.lashou.com/shenyang'],
    ['lashou', 'suzhou'] : ['拉手网-苏州', 'http://www.lashou.com/suzhou'],
    ['lashou', 'wuxi'] : ['拉手网-无锡', 'http://www.lashou.com/wuxi'],
    ['lashou', 'xian'] : ['拉手网-西安', 'http://www.lashou.com/xian'],
    ['lashou', 'zhengzhou'] : ['拉手网-郑州', 'http://www.lashou.com/zhengzhou'],
    ['lashou', 'dalian'] : ['拉手网-大连', 'http://www.lashou.com/dalian'],
    ['lashou', 'qingdao'] : ['拉手网-青岛', 'http://www.lashou.com/qingdao'],
    ['lashou', 'changsha'] : ['拉手网-长沙', 'http://www.lashou.com/changsha'],
    ['lashou', 'hefei'] : ['拉手网-合肥', 'http://www.lashou.com/hefei'],
    ['lashou', 'taiyuan'] : ['拉手网-太原', 'http://www.lashou.com/taiyuan'],
    ['lashou', 'fuzhou'] : ['拉手网-福州', 'http://www.lashou.com/fuzhou'],
    ['lashou', 'kunming'] : ['拉手网-昆明', 'http://www.lashou.com/kunming'],
    ['lashou', 'shijiazhuang'] : ['拉手网-石家庄', 'http://www.lashou.com/shijiazhuang'],
    ['lashou', 'jinan'] : ['拉手网-济南', 'http://www.lashou.com/jinan'],
    ['lashou', 'xiamen'] : ['拉手网-厦门', 'http://www.lashou.com/xiamen'],
    ['lashou', 'langfang'] : ['拉手网-廊坊', 'http://www.lashou.com/langfang'],
    ['lashou', 'nanchang'] : ['拉手网-南昌', 'http://www.lashou.com/nanchang'],
    ['lashou', 'fushun'] : ['拉手网-抚顺', 'http://www.lashou.com/fushun'],
    ['lashou', 'ningbo'] : ['拉手网-宁波', 'http://www.lashou.com/ningbo'],
    ['lashou', 'changzhou'] : ['拉手网-常州', 'http://www.lashou.com/changzhou'],
    ['lashou', 'haerbin'] : ['拉手网-哈尔滨', 'http://www.lashou.com/haerbin'],
    ['lashou', 'baoding'] : ['拉手网-保定', 'http://www.lashou.com/baoding'],
    ['lashou', 'shaoxing'] : ['拉手网-绍兴', 'http://www.lashou.com/shaoxing'],
    ['lashou', 'changchun'] : ['拉手网-长春', 'http://www.lashou.com/changchun'],



    ['meituan', 'beijing'] : ['美团-北京', 'http://www.meituan.com/beijing'],
    ['meituan', 'shanghai'] : ['美团-上海', 'http://www.meituan.com/shanghai'],
    ['meituan', 'guangzhou'] : ['美团-广州', 'http://www.meituan.com/guangzhou'],
    ['meituan', 'shenzhen'] : ['美团-深圳', 'http://www.meituan.com/shenzhen'],
    ['meituan', 'wuhan'] : ['美团-武汉', 'http://www.meituan.com/wuhan'],
    ['meituan', 'hangzhou'] : ['美团-杭州', 'http://www.meituan.com/hangzhou'],
    ['meituan', 'tianjin'] : ['美团-天津', 'http://www.meituan.com/tianjin'],
    ['meituan', 'nanjing'] : ['美团-南京', 'http://www.meituan.com/nanjing'],
    ['meituan', 'chengdu'] : ['美团-成都', 'http://www.meituan.com/chengdu'],
    ['meituan', 'chongqing'] : ['美团-重庆', 'http://www.meituan.com/chongqing'],
    ['meituan', 'shenyang'] : ['美团-沈阳', 'http://www.meituan.com/shenyang'],
    ['meituan', 'suzhou'] : ['美团-苏州', 'http://www.meituan.com/suzhou'],
    ['meituan', 'wuxi'] : ['美团-无锡', 'http://www.meituan.com/wuxi'],
    ['meituan', 'xian'] : ['美团-西安', 'http://www.meituan.com/xian'],
    ['meituan', 'zhengzhou'] : ['美团-郑州', 'http://www.meituan.com/zhengzhou'],
    ['meituan', 'dalian'] : ['美团-大连', 'http://www.meituan.com/dalian'],
    ['meituan', 'qingdao'] : ['美团-青岛', 'http://www.meituan.com/qingdao'],
    ['meituan', 'changsha'] : ['美团-长沙', 'http://www.meituan.com/changsha'],
    ['meituan', 'hefei'] : ['美团-合肥', 'http://www.meituan.com/hefei'],
    ['meituan', 'taiyuan'] : ['美团-太原', 'http://www.meituan.com/taiyuan'],
    ['meituan', 'fuzhou'] : ['美团-福州', 'http://www.meituan.com/fuzhou'],
    ['meituan', 'kunming'] : ['美团-昆明', 'http://www.meituan.com/kunming'],
    ['meituan', 'shijiazhuang'] : ['美团-石家庄', 'http://www.meituan.com/shijiazhuang'],
    ['meituan', 'jinan'] : ['美团-济南', 'http://www.meituan.com/jinan'],
    ['meituan', 'xiamen'] : ['美团-厦门', 'http://www.meituan.com/xiamen'],
    ['meituan', 'langfang'] : ['美团-廊坊', 'http://www.meituan.com/langfang'],
    ['meituan', 'nanchang'] : ['美团-南昌', 'http://www.meituan.com/nanchang'],
    ['meituan', 'fushun'] : ['美团-抚顺', 'http://www.meituan.com/fushun'],
    ['meituan', 'ningbo'] : ['美团-宁波', 'http://www.meituan.com/ningbo'],
    ['meituan', 'changzhou'] : ['美团-常州', 'http://www.meituan.com/changzhou'],
    ['meituan', 'haerbin'] : ['美团-哈尔滨', 'http://www.meituan.com/haerbin'],
    ['meituan', 'baoding'] : ['美团-保定', 'http://www.meituan.com/baoding'],
    ['meituan', 'shaoxing'] : ['美团-绍兴', 'http://www.meituan.com/shaoxing'],
    ['meituan', 'changchun'] : ['美团-长春', 'http://www.meituan.com/changchun'],


    }

